const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

// Short-lived check-in code generated by the instructor mid-session.
// The instructor displays the code (on screen or aloud); students
// enter it on their Attendance tab. Codes are 6 digits and expire
// in 10 minutes. Generating a new code for the same session
// supersedes the previous one (active = max created_at where
// expires_at > now).
const LiveSessionAttendanceCode = sequelize.define(
  'LiveSessionAttendanceCode',
  {
    id:              { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    live_session_id: { type: DataTypes.INTEGER, allowNull: false, references: { model: 'live_sessions', key: 'id' } },
    // 6-digit numeric (kept as STRING to preserve leading zeros and
    // because "code" semantically is text, not a number).
    code:            { type: DataTypes.STRING(10), allowNull: false },
    expires_at:      { type: DataTypes.DATE, allowNull: false },
    created_by:      { type: DataTypes.INTEGER, allowNull: false, references: { model: 'users', key: 'id' } },
  },
  {
    tableName: 'live_session_attendance_codes',
    timestamps: true,
    underscored: true,
    indexes: [
      { fields: ['live_session_id'] },
      // Lookup hot path: validating a student-entered code.
      { fields: ['code'] },
    ],
  }
);

module.exports = LiveSessionAttendanceCode;
